import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  party,
  enemy,
}: Readonly<{
  children: React.ReactNode;
  party: React.ReactNode;
  enemy: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-950 text-zinc-100 font-sans h-screen w-screen overflow-hidden flex`}
      >
        {/* Left Column: Party Sidebar */}
        <aside className="w-80 flex-shrink-0 border-r border-zinc-800 bg-zinc-900 p-4">
          {party}
        </aside>

        {/* Center Column: Main Battle Grid */}
        <main className="flex-1 relative">
          {children}
        </main>

        {/* Right Column: Enemy Area */}
        <aside className="w-80 flex-shrink-0 border-l border-zinc-800 bg-zinc-900 p-4">
            {enemy}
        </aside>
      </body>
    </html>
  );
}
