import { createCardId } from "@/modules/cards/cards.helper";
import type { ClassDefinition, HeroClass } from "./heroClass.types";

export const CLASS_REGISTRY: Record<HeroClass, ClassDefinition> = {
	HOBO: {
		id: "HOBO",
		name: "Hobo",
		spriteBase: "peasant", // Assuming you have a peasant_0.png!
		bonusMaxHp: 0,
		bonusBaseDef: 0,
		bonusBaseMove: 0,
		utilityCardChoices: [createCardId("bandage-1")], // Start with a basic heal
	},
	FIGHTER: {
		id: "FIGHTER",
		name: "Fighter",
		spriteBase: "squire",
		bonusMaxHp: 2,
		bonusBaseDef: 1,
		bonusBaseMove: 0,
		utilityCardChoices: [createCardId("shield-block-1")],
	},
	MAGE: {
		id: "MAGE",
		name: "Mage",
		spriteBase: "apprentice",
		bonusMaxHp: 0,
		bonusBaseDef: 0,
		bonusBaseMove: 0,
		utilityCardChoices: [createCardId("push-1")],
	},
	ROGUE: {
		id: "ROGUE",
		name: "Rogue",
		spriteBase: "rogue",
		bonusMaxHp: 0,
		bonusBaseDef: 0,
		bonusBaseMove: 0,
		utilityCardChoices: [],
	},
	ARCHER: {
		id: "ARCHER",
		name: "Archer",
		spriteBase: "archer",
		bonusMaxHp: 0,
		bonusBaseDef: 0,
		bonusBaseMove: 0,
		utilityCardChoices: [],
	},
	KNIGHT: {
		id: "KNIGHT",
		name: "Knight",
		spriteBase: "knight",
		bonusMaxHp: 0,
		bonusBaseDef: 0,
		bonusBaseMove: 0,
		utilityCardChoices: [],
	},
	BARBARIAN: {
		id: "BARBARIAN",
		name: "Barbarian",
		spriteBase: "barbarian",
		bonusMaxHp: 0,
		bonusBaseDef: 0,
		bonusBaseMove: 0,
		utilityCardChoices: [],
	},
	PYROMANCER: {
		id: "PYROMANCER",
		name: "Pyromancer",
		spriteBase: "pyromancer",
		bonusMaxHp: 0,
		bonusBaseDef: 0,
		bonusBaseMove: 0,
		utilityCardChoices: [],
	},
	CRYOMANCER: {
		id: "CRYOMANCER",
		name: " Cryomancer",
		spriteBase: "cryomancer",
		bonusMaxHp: 0,
		bonusBaseDef: 0,
		bonusBaseMove: 0,
		utilityCardChoices: [createCardId("ice-wall-1")],
	},
	CLERIC: {
		id: "CLERIC",
		name: "Cleric",
		spriteBase: "cleric",
		bonusMaxHp: 0,
		bonusBaseDef: 0,
		bonusBaseMove: 0,
		utilityCardChoices: [],
	},
};
