import { createCardId } from "@/modules/cards/cards.helper";
import type { ClassDefinition, HeroClass } from "./heroClass.types";

export const CLASS_REGISTRY: Record<HeroClass, ClassDefinition> = {
	HOBO: {
		id: "HOBO",
		name: "Hobo",
		spriteBase: "heroes/hobo",
		bonusMaxHp: 0,
		bonusBaseDef: 0,
		bonusBaseMove: 0,
		utilityCardChoices: [createCardId("bandage-1")],
	},
	FIGHTER: {
		id: "FIGHTER",
		name: "Fighter",
		spriteBase: "heroes/fighter",
		bonusMaxHp: 2,
		bonusBaseDef: 1,
		bonusBaseMove: 0,
		utilityCardChoices: [
			createCardId("shield-block-1"),
			createCardId("battle-cry-1"),
		],
	},
	MAGE: {
		id: "MAGE",
		name: "Mage",
		spriteBase: "heroes/mage",
		bonusMaxHp: 0,
		bonusBaseDef: 0,
		bonusBaseMove: 0,
		utilityCardChoices: [
			createCardId("arcane-shield-1"),
			createCardId("push-1"),
		],
	},
	ROGUE: {
		id: "ROGUE",
		name: "Rogue",
		spriteBase: "heroes/rogue",
		bonusMaxHp: 0,
		bonusBaseDef: 0,
		bonusBaseMove: 0,
		utilityCardChoices: [],
	},
	ARCHER: {
		id: "ARCHER",
		name: "Archer",
		spriteBase: "heroes/archer",
		bonusMaxHp: 0,
		bonusBaseDef: 0,
		bonusBaseMove: 0,
		utilityCardChoices: [],
	},
	KNIGHT: {
		id: "KNIGHT",
		name: "Knight",
		spriteBase: "heroes/knight",
		bonusMaxHp: 0,
		bonusBaseDef: 0,
		bonusBaseMove: 0,
		utilityCardChoices: [],
	},
	BARBARIAN: {
		id: "BARBARIAN",
		name: "Barbarian",
		spriteBase: "heroes/barbarian",
		bonusMaxHp: 0,
		bonusBaseDef: 0,
		bonusBaseMove: 0,
		utilityCardChoices: [],
	},
	PYROMANCER: {
		id: "PYROMANCER",
		name: "Pyromancer",
		spriteBase: "heroes/pyromancer",
		bonusMaxHp: 0,
		bonusBaseDef: 0,
		bonusBaseMove: 0,
		utilityCardChoices: [],
	},
	CRYOMANCER: {
		id: "CRYOMANCER",
		name: " Cryomancer",
		spriteBase: "heroes/cryomancer",
		bonusMaxHp: 0,
		bonusBaseDef: 0,
		bonusBaseMove: 0,
		utilityCardChoices: [createCardId("ice-wall-1")],
	},
	CLERIC: {
		id: "CLERIC",
		name: "Cleric",
		spriteBase: "heroes/cleric",
		bonusMaxHp: 0,
		bonusBaseDef: 0,
		bonusBaseMove: 0,
		utilityCardChoices: [],
	},
};
